import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import AuthProvider from "../providers/AuthProvider";
import Header from "@/components/layout/Header";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";
import { StoreStatusBanner } from "@/components/StoreStatusBanner";

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="pt-BR">
      <body className={`${roboto.className} antialiased`}>
        <AuthProvider session={session}>
          <Header />
          <StoreStatusBanner />
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
